version: '3.7'
x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '1m'
    max-file: '1'
    tag: '{{.Name}}'

services:
  backend:
    container_name: cpe-kmutt-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      WAIT_HOSTS: mongo:27017
      TZ: Asia/Bangkok
      ORIGIN: http(|s):\/\/localhost:5000
      DATABASE_CONNECTION: 'mongodb://mongodb:27017/cpe-kmutt-web'
      DATABASE_USERAME: root
      DATABASE_PASSWORD: cpeKMUTT@WebSite
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: very-secret-key.jwt
      JWT_EXPIRES: 3600s
      OPS_KEY: 'CPE-KMUTT.opskey'
      NODE_ENV: 'development'
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - './backend:/backend'
    links:
      - mongodb
    command: yarn start:dev
    depends_on:
      - mongodb
  frontend:
    container_name: cpe-kmutt-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      TZ: Asia/Bangkok
      STRAPI_ENDPOINT: http://localhost:1337
      APP_GRAPHQL_ENDPOINT: http://strapi:1337/graphql
    ports:
      - 5000:3000
      - 49153:49153
    volumes:
      - './frontend:/frontend'
      - /frontend/node_modules
    depends_on:
      - strapi
  strapi:
    container_name: cpe-kmutt-strapi
    restart: on-failure
    build:
      context: ./strapi
      dockerfile: Dockerfile
      target: dev
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: cpeKMUTT@WebSite
    volumes:
      - ./uploads/:/app/public/uploads
      - ./strapi/components/:/app/components
      - ./strapi/config/:/app/config
      - ./strapi/plugins/:/app/plugins
      - ./strapi/api/:/app/api
      - ./strapi/extensions/:/app/extensions
    ports:
      - '1337:1337'
    depends_on:
      - mongodb
    logging: *default-logging
  mongodb:
    container_name: mongodb
    restart: on-failure
    image: 'bitnami/mongodb:5.0.9'
    environment:
      MONGODB_ROOT_PASSWORD: cpeKMUTT@WebSite
      TZ: Asia/Bangkok
    ports:
      - '27017:27017'
    volumes:
      - './db:/bitnami'
