version: '3.8'
services:
  proxy:
    container_name: proxy
    restart: unless-stopped
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - strapi
      - mongodb
      - frontend
    environment:
      STRAPI_ADMIN_EMAIL: ${STRAPI_ADMIN_EMAIL}
      PROXY_DOMAIN: ${PROXY_DOMAIN}
    volumes:
      - './cert:/etc/letsencrypt'
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      TZ: Asia/Bangkok
      STRAPI_ENDPOINT: ${STRAPI_ENDPOINT}
      APP_GRAPHQL_ENDPOINT: ${APP_GRAPHQL_ENDPOINT}
    depends_on:
      - strapi
  backend:
    container_name: cpe-kmutt-backend-prod
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      WAIT_HOSTS: mongo:27017
      TZ: Asia/Bangkok
      ORIGIN: '${BACKEND_ORIGIN}'
      DATABASE_CONNECTION: 'mongodb://mongodb:27017/cpe-kmutt-web'
      DATABASE_USERAME: root
      DATABASE_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES: 3600s
      OPS_KEY: '${OPS_KEY}'
      NODE_ENV: 'development'
      PORT: 3000
    volumes:
      - './backend:/backend'
    links:
      - mongodb
    command: yarn start:dev
  strapi:
    container_name: cpe-kmutt-strapi-prod
    restart: unless-stopped
    build:
      context: ./strapi
      dockerfile: Dockerfile
      target: prod
      args:
        APP_TINY_MCE_KEY: '${STRAPI_TINY_MCE}'
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: '${MONGODB_ROOT_PASSWORD}'
    ports:
      - '1337:1337'
    volumes:
      - ./uploads/:/app/public/uploads
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: 'bitnami/mongodb:5.0.9'
    restart: unless-stopped
    environment:
      MONGODB_ROOT_PASSWORD: '${MONGODB_ROOT_PASSWORD}'
      TZ: Asia/Bangkok
    volumes:
      - './db:/bitnami'
